### PR TITLE
extract submitted date to support slack reader reqs

### PR DESCRIPTION
**Pull request by isnbh0**
Hi, thanks for hosting this feed.

As in #3 I was also failing to sub to this in Slack and trying to get it to work. (I thought https://github.com/snarfed/granary/pull/847 would solve it but I was wrong)

My next hunch for what might help comes from https://github.com/GoogleChrome/developer.chrome.com/issues/2808 --
- extracting and including item publish dates when possible
- sorting items by publish date decreasing

Hopefully this will make it subbable in Slack 🤞

Thanks again!

### CODE REVIEW

**Comment by capjamesg** [comment]
Thank you for your contribution, @isnbh0! I will merge and deploy this now.

**Comment by capjamesg** [comment]
This change is now deployed at https://jamesg.blog/hf-papers.json. Let me know if things work as you expect!

**Comment by isnbh0** [comment]
It worked! The Slack RSS reader was finally able to successfully fetch items 🎉 Thanks again!!

**Comment by capjamesg** [comment]
Yay! I'm glad everything works!

**Pull request merged**
